version: '3.8'

#secrets:
  # Secrets are single-line text files where the sole content is the secret
  # Paths in this example assume that secrets are kept in local folder called ".secrets"
 # DB_ROOT_PWD:
 #   file: .secrets/db_root_pwd.txt
 # MYSQL_PWD:
 #   file: .secrets/mysql_pwd.txt

services:
  nginx:
    image: nginx:latest
    container_name: nginx_container
    restart: always
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  app:
    container_name: app
    build: ./
    ports:
      - "8081:8081"
    #env_file:
    #  - variables.env
    #depends_on:
    #  - "api"

volumes:
  db:
    driver: local