services:
  db:
    hostname: db
    image: postgres
    ports:
      - 11432:11432
    expose:
      - 11432:11432
    restart: always
    environment:
      - POSTGRES_DB=configcatdb
      - POSTGRES_USER=configcat
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql