services:
  db:
    hostname: db
    image: ankane/pgvector
    ports:
      - 5432:5432
    expose:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_DB=chatdb
      - POSTGRES_USER=n8nchat
      - POSTGRES_PASSWORD=Blade1708
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql